spring.application.name=auth-service

# Port
server.port=8081

# Database SQL Server - instance SQL2025
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQL2025;databaseName=auth_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT - secret key
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# Consul Discovery Configuration
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.register-health-check=true

//health
# Cho phép Consul g?i /actuator/health ?? khám s?c kho?
management.endpoints.web.exposure.include=health

# --- C?U HÌNH LOGGING ---
logging.level.root=INFO


logging.level.com.example.auth-service=DEBUG


logging.file.name=logs/auth-service.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
springdoc.api-docs.path=/api/auth/v3/api-docs
