spring.application.name=payment-service
server.port=8085

# ========== DATABASE ==========
spring.datasource.url=jdbc:sqlserver://localhost\\SQL2025;databaseName=mini_ecommerce_payment;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ========== JPA ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ========== RABBITMQ ==========
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ========== CONSUL ==========
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.register-health-check=true
spring.cloud.consul.discovery.prefer-ip-address=true

# ========== ACTUATOR ==========
management.endpoints.web.exposure.include=health

# ========== LOGGING ==========
logging.level.root=INFO
logging.level.com.example.payment_service=DEBUG
logging.file.name=logs/payment-service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ========== SWAGGER ==========
springdoc.api-docs.path=/api/payments/v3/api-docs

# ========== VNPAY ==========
# TODO: Thay DEMO1234 bằng TmnCode thật từ email VNPAY Sandbox
vnpay.tmn-code=8JXF7BVX
# TODO: Thay bằng HashSecret thật từ email VNPAY Sandbox
vnpay.hash-secret=T2HZ94ZP399RHAAQE3XWV7IVNW1D6UA4
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# URL ngrok để VNPAY goi callback ve localhost cua ban
vnpay.return-url=https://sclerotomic-viewlessly-nyla.ngrok-free.dev/api/payments/vnpay-callback
