spring.application.name=user-service

server.port=8088

# Database configuration
spring.datasource.url=jdbc:sqlserver://localhost\\SQL2025;databaseName=mini_ecommerce_user;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Consul Discovery Configuration
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.register-health-check=true

# Allow Consul to call /actuator/health
management.endpoints.web.exposure.include=health
debug=true

# --- CAU HINH LOGGING ---
# 1. Level log chung toan du an
logging.level.root=INFO

# 2. Level log chi tiet
logging.level.com.example.user_service=DEBUG

# 3. Noi luu tru file log
logging.file.name=logs/user-service.log

# 4. Dinh dang console logger
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
springdoc.api-docs.path=/api/users/v3/api-docs

# Force 127.0.0.1 as the discovery address to avoid WSL/Hyper-V adapter issues
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.ip-address=127.0.0.1
