spring.application.name=order-service
server.port=8083

# Database configuration (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost\\SQL2025;databaseName=mini_ecommerce_order;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Consul Discovery Configuration
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.register-health-check=true

# Allow Consul to call /actuator/health
management.endpoints.web.exposure.include=health

# --- C?U HINH LOGGING ---

logging.level.root=INFO

logging.level.com.example.order_service=DEBUG

logging.file.name=logs/order-service.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
springdoc.api-docs.path=/api/orders/v3/api-docs
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Force 127.0.0.1 as the discovery address to avoid WSL/Hyper-V adapter issues
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.ip-address=127.0.0.1
