spring.application.name=order-service
server.port=8083

# Database configuration (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost\\SQL2025;databaseName=mini_ecommerce_order;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Consul Discovery Configuration
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.register-health-check=true

# Allow Consul to call /actuator/health
management.endpoints.web.exposure.include=health

# --- C?U HÌNH LOGGING ---
# 1. Level log chung toàn d? án
logging.level.root=INFO

# 2. Level log chi ti?t (ch? b?t log.debug() ? code c?a b?n)
# L?u ý s?a ch? 'product_service' kh?p ?úng tên package c?a b?n
logging.level.com.example.order_service=DEBUG

# 3. N?i l?u tr? file log
logging.file.name=logs/order-service.log

# 4. ??nh d?ng ch? lúc in ra cho ??p
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
springdoc.api-docs.path=/api/orders/v3/api-docs
