server:
  port: 8082
  servlet:
    context-path: /
  prefix: author

spring:
  profiles:
    active: @active.mode@
    include:
      - @profile.include@
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: ${config.service-name}
  cloud:
    consul:
      host: 127.0.0.1
      port: 8000
      config:
        enabled: false
      discovery:
        enabled: true
        health-check-path: /actuator/health
        instance-id: ${config.service-name}
        service-name: ${config.service-name}
        prefer-ip-address: true
        prefer-agent-address: false
        health-check-interval: 25s
        health-check-critical-timeout: 90s
        register: true
        deregister: true
  jpa:
    open-in-view: false

config:
  service-name: ev-authorization-service
  api:
    version: v1