server:
  port: 8081
  servlet:
    context-path: /
  prefix: authn

spring:
  application:
    name: ${config.service-name}
  profiles:
    active: @active.mode@
    include:
      - @profile.include@
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
      enabled: true

config:
  channel:
    app: APP
    web: WEB
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 86400000
      public-key: "-----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjmxokHdnQJ4/BoC+T6ZD
        Yj7ARDvTP90JppntiAw6U3wi0zvp0ZaKN8OE1rdAAy+p6jTFUJuhNw/8YA40n0Cf
        5e8Q/cnEiKmvXulkMP2T0mmEXS0ivpyXkn0x9Jmy/hugoDMH42N6XDWrntlCFtAo
        sh5Mr1NO/lM6IAK/sj8AHvvq7OG5txv/2FLzwDm+BEwsTR9E7zo+KpBXE/j8+4lS
        dMeNoPLSeJVUt+DSOF5lpZZI+lacB/Lof9X60r5QaTq3J2SkvzjsHlgfHP79pqHD
        gpLcxRjPscF1tGUktlIGkbZ/5eMaPYleVMRxCqEDh01zQ4syIX2h7mWJDklEzOWH
        EwIDAQAB
        -----END PUBLIC KEY-----"
      private-key: "-----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCObGiQd2dAnj8G
        gL5PpkNiPsBEO9M/3Qmmme2IDDpTfCLTO+nRloo3w4TWt0ADL6nqNMVQm6E3D/xg
        DjSfQJ/l7xD9ycSIqa9e6WQw/ZPSaYRdLSK+nJeSfTH0mbL+G6CgMwfjY3pcNaue
        2UIW0CiyHkyvU07+UzogAr+yPwAe++rs4bm3G//YUvPAOb4ETCxNH0TvOj4qkFcT
        +Pz7iVJ0x42g8tJ4lVS34NI4XmWllkj6VpwH8uh/1frSvlBpOrcnZKS/OOweWB8c
        /v2mocOCktzFGM+xwXW0ZSS2UgaRtn/l4xo9iV5UxHEKoQOHTXNDizIhfaHuZYkO
        SUTM5YcTAgMBAAECggEAITKLvQDYBGvebPmdYptyoXfXARCg0QYItdizUT7oaYVJ
        6MrSWZQpa44bbKESPqvhg0IBrCRak6caQJmPEn/RxZrP7xgUw3Yp9omYXQL+bdFC
        lSVsL9n4SqD7//PDkQ+HhU/fytTpNI0eD8y8ZuzmT35YiZV1mDp2FfgODtI4iP/+
        T5DHHPJkrMtTZhFCqtSvkffkDKDurvdIxTnfc3K77xrcSaY9/FBmQasS1qfBEGFn
        UEPmG+JDBadkU7iUf36zCcdDwgS/cj7cZ4DkctfxseCqxl5/0ZWQvNTkbaHXy10n
        DT3jQOnOuaXmO+Q2q1v6yiYf7SGIU2dxIn3oVPl/gQKBgQDG1G+saxd6huAMIKdB
        4s2TQFguT6xV0cMIbamTuBVypXiaMqgN8/lyaUq0E2S2yx2RlLRw2ym/SE5kfLWC
        KbDK6RLXQFiZkOrk/bGkvvp16lOwjE/6hQ+K6szjEXvKO/GEVT6YflbUE/go52k0
        XMw/FwtgKQJyufOqPoCIlihMowKBgQC3X/w6yJtz1gpljjMVkYSXMg6lZTgMrjyF
        EnUjulVAGxOAqU5Tl1aYd/2bzYVAPwwPhIyLTeTdM96QLxKn52dKjRyvx0OB0+gw
        S7k0YE6Kw/ra3A5gZrj71z4CMCky7h7EShud2pijRAFOnBrf/6BFbselI0p+bCdA
        2VGjBy6S0QKBgAJyxTlDTFO263VaxZR7HXrttOhFFOMtpRAqgYcPIjx6KyUC8KzT
        T0QIZeIXxwq1L5UGVr55BGeVlVmJa5bBuqqU+iVqZmzlqu7M7O4RZ/Yhv4wR/j4g
        e1ODlqhJI9QWrt+pSQ8JpzoPUOP4DYSWi/FO8FXry1rsTULQaDbGWpKvAoGBAJf2
        1IlGjAUP4SfOEymRoWbHFfodCrj/f6nr5OWJ2nI4vg3GwOFnLl1GOwZt6DqYxP7r
        IqmjEMH75TppuDUrAJ94l8hYAurJWMcFSeNM2GoJBY9wA/4BwtT5yCp6DPpm+VpD
        6+UCLbJHfinOFjuBlSlVJ+ADgg2IxXLpZc0L+52xAoGBAIYh42j+0UCRkiiwZ23h
        qaluDk5u165aSB41ce/RlSz6U5mGQEMgiSI8K5lEft/zqnZSzJXZ6mdn1hRZoyyf
        abcx5UjFe19DxMFxw29RASHQqQrJTQuyc43p/EWTSLsLK7RI7LZmeOBsD4zC/eg0
        qlpkOUUwPrin9eRvYJsK0Srb
        -----END PRIVATE KEY-----"
      issuer-client-name: "lopa-auth-client-key"
  otp:
    return-raw-value: true
    length: 6
    validity: 180
    #todo change when need
    max-fail-count: 5
    lock-time (m): 30
    secret-key: 2~wsL|b4*F50
  login:
    failed_login_limit: 5
    lock_for_first_time(m): 5
    lock_next_time(m): 15
